development:
  adapter: postgresql
  username: postgres
  host:     127.0.0.1
  encoding: unicode
  database: vintography_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: vintography_test
  pool: 5
  timeout: 5000

production:
  uri: <%= ENV['DATABASE_URL'] %>
